Backbone:
  module_name: models.resnet.ResNet
  class_name: resnet18

Datasets:
  train_path: Brodatz/train
  val_path: Brodatz/val
  test_path: Brodatz/test
  Batch_size: 32

Parameters:
  max_epochs: 100
  learning_rate: 0.001

Classifier:
  module_name: models.classifier
  class_name: Classifier
  num_classes: 10
  in_features_dim: 512